### ISSUE TITLE
Environment Analysis

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#13]

**Comment by tortmann** [comment]
I left my comments in the document - marked in yellow

**Comment by dietrich14** [comment]
this task was actually not yet ready for review, however thanks already for the fast review ;)

**Comment by tortmann** [comment]
i am sry about that i already saw it beeing uploaded and the other document is much longer so i started with this one ;)

**Comment by dietrich14** [comment]
version 2 can be found on sharepoint in folder BusinessPlan\Umweltanalyse_v2

changes:

- added EU-DSGVO to the legal factors 
- added a short paragraph about innovation management to the technical factors and referenced to the competitor analysis for further details since it is covered there in more detail

**Comment by Graf-Carello** [comment]
I corrected some small typos, otherwise the doc seems done in my opinion.

**Comment by tortmann** [comment]
**Approved** 

Thank you very much for commenting on the changes made, this makes it so much easier for me.
