### ISSUE TITLE
Profit Model

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#16]

**Comment by NSpalek** [comment]
Ready for review.
Can be found on SharePoint: Dokumente\BusinessPlan\Ertragsmodell_v1.docx

To-Do:
> Check\Discuss if we need to define exact prices. (Very hard to calculate)

**Comment by tortmann** [comment]
I highlighted a couple of points that should be discussed in more detail during our next team meeting to discuss their necessity or level of detail. In general however it is well done and will be approved after the some potentially minor changes following the next meeting. Additionally the necessity for a cost revenue estimate should be discussed at it directly influences the revenue model mentioned in this task.

**Comment by NSpalek** [comment]
Ready for second review.
Can be found on SharePoint: Dokumente\BusinessPlan\Ertragsmodell_v2.docx

**Comment by Graf-Carello** [comment]
The changes @NSpalek implemented should now reflect our discussions about the revenue model. I also proofread the document, and it seems good to me. I just corrected some tiny typos. It now states all important aspects about EasyBiz's revenue streams, except any detailed real numbers or percentages, since we don't need this for our project.

**Comment by tortmann** [comment]
Thank you for the changes. I reviewed it and also corrected some minor typos and the document is now approved and can be added to the large complete document.
