### ISSUE TITLE
Extend/Adapt Data model (Prereq. for Implem.)

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#29]
Check RBAC model in master theses on p.48
This concept should be fine and only the adaption of tables for Users, companies and the platform for buying/selling/reviewing processes is needed.

**Comment by amarbajric** [comment]
This task does NOT require a PR.
Only modeling and reviewing will be done.

**Comment by amarbajric** [comment]
**DONE:**
- first adaptions/discussions written down in a document
- made some considerations about the existing data model and how to adapt/extend it
- short excerpt of the two tables recommended and one optional table to adapt/extend/add as an ER-Diagram

> File can be found on the SharePoint in the `/Development/Data_model` directory.


**ToDo:**
- @tortmann I need a review from you and your thoughts on my considerations and what you think? Do you see any problems/issues with the recommended approach?
- @loete I also need a review from you and what you think about my considerations? We have roughly discussed it already but now I have outlined all necessary points.

In general, feedback and refinement suggestions are requested from my side (if any).
If however no refinement and further work on the modelling task is needed, the task can be commented (with a short approval) and closed. The next step will then be to implement the data model and the needed services.

**Comment by tortmann** [comment]
##### 1) ad User:

- AuthenticationService definitely needs to be linked to the DB (- user table)
- whether or not it's better to use the existing roles/rules and extend them or create additional access control entities should be discussed during the next meeting
- only exisiting users that have a verified payment for premium services (just a bool required for our purposes) should be able to create organizations
          - one register process to create an account which can then be **extended:**
                         + add premium service
                         + join / create organizations
                         + add / buy process models
                         + execute process models

##### 2) ad Organization:

I would suggest a structure similar to the one below:

`User {organization:organizationId, premium:boolean, execution:boolean}`
`SystemUser` (can approve/manage processes for/in the process store - not linked to an org)
`SystemAdmin`
`Organization {normalUsers[userId], privilegedUsers[userId], creator:userId}`

##### 3) ad Process Store:

In my opinion a process store should definitely be implemented to differentiate between the different states a process model can be in. Therefore, I would suggest a structure similar to the one below:

`Process {organizations[organizationId], public:boolean, active:boolean, reviewed:boolean}`

`Store {processes[processId]`

This model creates a process store that can be used by Users/Organizations and SystemUsers and includes access control parameters.


##### I would be happy to further discuss these suggestions and thoughts in the comments

**Comment by amarbajric** [comment]
> whether or not it's better to use the existing roles/rules and extend them or create additional access control entities should be discussed during the next meeting

We will definitely need more roles and rules to allow organizations for a better RBAC control. 
- Maybe we could also implement the feature of defining custom roles within an org. by putting together predefined rules?

> only exisiting users that have a verified payment for premium services (just a bool required for our purposes) should be able to create organizations

I totally agree with you! This is a required feature/implementation and should be considered. Thank you!

> 2) ad Organization:
> I would suggest a structure similar to the one below:

I do not agree fully with all points mentioned.
- If users have an attribute `organizationId` and `execution` (idk what the purpose of this attribute is?) , are the SystemUsers separated from the other Users? If so, I have to disagree as I would suggest to put all users, regardless if its an approver, admin or normal user, into the same table.
- Users which are acting as admins or have other roles specific to the system, do not need to be linked to an organization. I agree!
- I dont quite understand the separation of `normalUsers` and `privilegedUsers` in the Organization structure? Why is this necessary? We can distinguish users and their "privilege" by looking at their role(s) and the associated rules?

> 3) ad Process Store:
> In my opinion a process store should definitely be implemented to differentiate between the different states a process model can be in.

I have left this point open in order to reconsider it in the team. However, I fully support your suggestions to implement a separate table and to have one for the store with additional attributes.
- The `Process` table would be the pre-table before configuring the process within an org. for instantiating. If this happens, then the process is inserted into the existing `ProcessModel` table.
- The `Store` table also makes sense and can help us to persist additional data for the whole store.

Thank you for your review and your considerations @tortmann. My comment should serve as a reply on your thoughts and should help us in the plenum discussion. After the discussion at the next meeting, I will refine the document and republish it on the SharePoint to serve as a guideline.

**Comment by tortmann** [comment]
>If users have an attribute `organizationId` and `execution` (idk what the purpose of this attribute is?) , are the SystemUsers separated from the other Users? If so, I have to disagree as I would suggest to put all users, regardless if its an approver, admin or normal user, into the same table.

Yes it definitely makes more sense to put them into one table and differentiate via a `type` attribute.

>`execution` (idk what the purpose of this attribute is?) 

This should indicate wheter or not this user can execute process models - on second thought however it makes much more sense to associate this with an organization.

>I dont quite understand the separation of normalUsers and privilegedUsers in the Organization structure? Why is this necessary? We can distinguish users and their "privilege" by looking at their role(s) and the associated rules?

I wasn't completely sure wheter this would be possible by simply linking the new user table and the existing roles/rules that's why I brought it up

>I have left this point open in order to reconsider it in the team. However, I fully support your suggestions to implement a separate table and to have one for the store with additional attributes.

yes this will definitely be discussed during the next meeting

Thank you a lot for your feedback @amarbajric and I am looking forward to discussing this issue in more detail with the other team members during the next meeting

**Comment by amarbajric** [comment]
Thank you @tortmann for your time on this issue and your feedback concerning this topic.
I am also looking forward to the discussion with the other members on this specific topic and other upcoming topics. However, again thank you for your input. Much appreciated!

**Comment by amarbajric** [comment]
**UPDATE (15.04.2018)**
- revision of the initial data model proposal was done
  - Participants: @amarbajric & @mwageneder 
- changes were documented and published under a new file on the SharePoint
  - Filename: `data_model_adaption_v2.pdf`
  - includes all considerations and needed adaptions in a well-formed structure
  - includes a new revised and adapted excerpt of the data model which shows also mappings to already existing entities

**ToDo**
- review needed from @tortmann 
- review needed from @loete 
- review needed from @mwageneder 
  - just a check needed if everything is included what has been discussed during our call!

**Comment by mwageneder** [comment]
**Review on: `data_model_adaption_v2.pdf`**

First of all, thank you very much for summarizing our discussion about the data model. You already identified the key points we have to adapt in order to fit our needs and listed them in your first summary. We only had to sharpen it a little bit and added a few points and now it should fit our needs. From my point of view, everything I can think of by now and all issues we discussed are included and I am very happy with it and again thank you for summarizing it.

As @amarbajric and I also discussed, the key features a user can do and the procedure of how registration, buying and instantiating a process for our customers is handled, will be created in a few days and uploaded to our Sharepoint on `Prozesse/Hilfsprozesse/...`. Therefore, a small process will show, how the procedure should look like mainly for our developer team to understand how we have planned to develop it.

**Comment by amarbajric** [comment]
Thank you for your first "review" @mwageneder!
Besides, I also like the idea of creating some supportive processes to give especially the SWD-Team an idea about all the procedures that the platform application should feature at the end.

**Comment by stfnltnr** [comment]
Checked my assumption according user data and recognized that there is no password column within the current usertable :poop: So we have to make some adjustments that the user data is read from the db instead of the *.csv files. As I have seen you already had some thoughts on this issue and added the missing columns to the user table.

Everything else looks very promising to me, imo we should implement/modify the data model that way.

**Comment by tortmann** [comment]
@amarbajric @mwageneder  Thank you for the very detailed and well done data model and documentation. In my opinion everything important is considered and documented for the time being.

> a process for our customers is handled, will be created in a few days and uploaded 
Supporting processes are definitely a great idea and should help the members of the dev team to better understand the underlying processes

@loete 
> Everything else looks very promising to me, imo we should implement/modify the data model that way.

Since everybody has now approved the current version of the data model I will close the issue.
