### ISSUE TITLE
Fix GUI-dev errors and resolve issues

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#44]
The `GUI` (frontend) uses an outdated version of Angular. Would be highly recommended to upgrade to the latest Angular version.
- Upgrade Angular 2.x to 5.x
- Check and fix possible dependency breaks
- Test if frontend still works

[OPT/HD]: This task is optional but highly desirable. If it takes to long, we need to discard this task/issue

**Comment by deKilla** [comment]
First I tried to update to angular5 in the according #44 branch which turned out to be a bad idea. Several dependencies inside the project haven't been updated to work with Angular5 and replacements are either not available at all or if they are, implementing them would be a lot of work.

On [1] I tried to get the project running while staying at Angular2. Note that this branch is derived from the #44 branch, so once it is running it first needs to be merged into the #44 before the #44 can then be merged into the dev.

The current status is that I (unsuccessfully) tried to upgrade webpack and it's dependencies which now breaks the dev configuration (issue with loaders).

[1] https://github.com/deKilla/IPPR2016/tree/planB

**Comment by amarbajric** [comment]
Thank your for your information and update regarding this issue @deKilla.
Ofc you can tinker around in the branches you created in your forked repository. However, as everyone has the rights to create new branches in my repository, we should avoid to fork the repository and then work in separate repos. In this form of collaboration we should use one repo.  So next time if you need another branch (i.e. sub-branch of a main feature-branch) just create one and label, name it like that.

Nevertheless, thank you for your description.
I will now have a look into this problem and hopefully fix the issue ASAP.

**Comment by tortmann** [comment]
> **ToDo**
make further investigations to fix pending error(s)
maybe consider updating whole frontend and start from scratch
ofc we could take the existing code and implement it in a fresh frontend set-up.
Link to the new ngx-admin (currently ng2-admin is used in our project)

Pasted ToDo (by @amarbajric ) from #64 to not forget it while #44 stays in progress

**Comment by amarbajric** [comment]
@tortmann Thank you for the ToDo!
- Issue was renamed to not cause confusion within dev-team
- Further ToDos can be found in the comment above ^
