### ISSUE TITLE
UserPage - Dashboard component

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#52]
Implement a dashboard which allows logged-in users to get an overview about:
- active process instances they are involved in
- active process instances (if they are "boss" of company)
- start/stop/manage process instances (if role allows for this actions)
- accounting - how much costs are the running instances generating (if role allows for this view)
- other key figures

Should be as modular as possible. (split in subcomponents if possible/needed)

**Comment by deKilla** [comment]
the news segment has been implemented redundantly - it is also part of the homepage that I've created yesterday (according to the sketches)
The toast placement is not optimal (minor issue)
When I create a new company I'm not directly part of it (is this intentional?)
Arguably modals and other reusable components could/should be placed in @theme but at the current state of the project, I guess this does not matter anymore.
Other than that I think you did a great job and I like it thus far. Full functionality is apparently not given but I don't know if this at all possible at the moment.

**Comment by amarbajric** [comment]
> the news segment has been implemented redundantly - it is also part of the homepage that I've created yesterday (according to the sketches)

Thats no problem at all. Redundancy is easier to remove than having no implementation at all.

> When I create a new company I'm not directly part of it (is this intentional?)

PR (from me) is coming in a few minutes which will fix this issue.

> Arguably modals and other reusable components could/should be placed in @theme but at the current state of the project, I guess this does not matter anymore.

No this does not matter anymore and is obsolete. The whole project would need a huge refactor but this is not feasible anymore.

Please comment under the actual PR @deKilla :)

**Comment by tortmann** [comment]
Everything was implemented as discussed today, and I can agree that backend changes will solve the above-mentioned issue when creating an organization.

Please don't close this issue until the endpoint connection placeholdersare acutally implemented tomorrow
