### ISSUE TITLE
Business Plan Document - LaTeX

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#66]
Combine all individual Business Plan and Process files into one large file.

**Comment by tortmann** [comment]
Please do not forget to update references to other files / chapters within each individual file by referencing the respective chapters etc. The Business processes should also be included in my opinion since they model the internal business logic and serve as a nice example for the processes mentioned in the business plan documents.

**Comment by dietrich14** [comment]
I'm going to list all the documents I've already added to Latex - so if there are any changes to be made in any of them, please let me know since I have to adapt it in the tex-files.
@tortmann do you agree with this approach of listing the documents here or would you have a more sophisticated solution of doing this? maybe move the documents to an own folder on SP?

**Comment by tortmann** [comment]
**Please list ALL documents** including the information whether or not it is already included for every document **in a comment here** and **edit the comment when you add documents to the LaTeX document**.

The file/folder structure on ShP will be optimized by me at a different point in time, most likely after all documents of the BP Team have been merged.

In general, all the documents that have the status "DONE" in waffle can by added in my opinion since they are all approved to be merged.

**Comment by tortmann** [comment]
This document **does not need to be finished until 25.04. but rather until 27.04.** to be distributed the evening before or during the interim presentation to the customer (RS).

**I added @Graf-Carello and @NSpalek for additional proofreading** after the document has been finalized. This will be discussed also during the next meeting(25.04.)

@dietrich14 Do you think this deadline is feasible?

**Comment by dietrich14** [comment]
I'll try to finish it ASAP, however the 27th should be feasible (if I'm able to include all the analyses from Excel properly). 
Furthermore I'd like to discuss the general structure of the document in the whole group during tomorrow's meeting.

**Comment by tortmann** [comment]
> Furthermore I'd like to discuss the general structure of the document in the whole group during tomorrow's meeting.

Of course, I will definitely reserve a timeslot for that.

**Comment by dietrich14** [comment]
added following documents to Latex:

- BusinessModel_v1
- BusinessModel_3Pillars_v1
- VisionStrategy_v2
- ConceptImplementation_v1
- PlatformFunctionality_v1
- ManagementSummary_v2
- Kundenbindung_Marketing_Kommunikationsstrategie_v2
- Ertragsmodell_v2
- Umweltanalyse_v2
- The-Transformative-Business-Model_v2
- Branchenstrukturanalyse_FiveForces_v1
- SWOT_v1
- ValuePropositionCanvas_v2
- business_model_canvas_v1
- Teambeschreibung_v1
- Risikoanalyse_v2

**ALL FILES FROM THE BUSINESS PLAN HAVE BEEN ADDED TO LATEX - PLEASE DO NOT UPDATE THEM ON SHAREPOINT ANYMORE**

**first version can be found on Sharepoint:**
https://fhjoanneum.sharepoint.com/:b:/s/EBUSA-Projekt/Ecz9JIlsjoBJv-kolQzny-oB39ZuAdzAiLe-8WpaXuEyZw?e=IvhNre


@mwageneder please do not make any further changes in the word documents of the process descriptions on SP since I'll start adding them from now on 


**Version 2 can be found on Sharepoint:**
https://fhjoanneum.sharepoint.com/:b:/s/EBUSA-Projekt/ERFs-GjviLVHmuf6GN0W7dIBxcT5i9xF0Ksk2YwsnJD6bw?e=WrdkKR

> changes:
> - inserted team description
> - added internal and external processes

**TODO**
- add sources
- adapt order of chapters
- adjust text size of EasyBiz in the title

@tortmann FYI

**Comment by dietrich14** [comment]
ready for review - document can be found on Sharepoint: BusinessPlan/easybiz_geschaeftsmodell_v3

@NSpalek @Graf-Carello 
please read through the document and especially check
- correct references (are there any missing / wrong)
- consistent gendering
- layout
- dependency of chapters - do any chapters have to be moved for better understanding

**Comment by NSpalek** [comment]
@dietrich14 
I have read through the document and highlighted a couple of mistakes.
I also have commented on most of them directly in the document.
Please feel free to ask if something is unclear.

The corrected document can be found on Sharepoint: BusinessPlan/easybiz_geschaeftsmodell_v3_Korr_Spalek.pdf

**Comment by Graf-Carello** [comment]
I have also read through the whole document (the version with @NSpalek  suggestions) and added some comments and marked errors with green color (same as Nina). 
So this file combines both Ninas  and my own suggestions for corrections in the whole document. 

The file is saved on Sharepoint:
BusinessPlan/easybiz_geschaeftsmodell_v3_Korr_Spalek_Graf.pdf
