### ISSUE TITLE
Internal Processes

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#8]
5 internal processes
BPMN
incl. description

**Comment by mwageneder** [comment]
Registrierung DONE
Upload-Validierung DONE

**Comment by mwageneder** [comment]
3/5 - Modellkauf DONE

**Comment by mwageneder** [comment]
4/5 Instanzkauf DONE
5/5 Änderungsanfrage DONE

**Comment by tortmann** [comment]
##### Review#1 done - 03.04.2018
Added comments in all `.pdf` and `.docx` documents for a review of the author(@mwageneder) with the request for changes and short feedback in case of discussions/questions issued in the commentary

#### The necessity for an English version of all processes and their descriptions should be discussed with our customer RS (see issue #56)

**Comment by mwageneder** [comment]
Since the Business Case is written in German the Author of the Business Processes chose German as well. If the Processes or the Documentation is needed in English, do not hesitate to contact the Author (@mwageneder) for an update.

Reviewed all Change requests within `.pdf` and `.docx` documents from @tortmann and implemented them within a new folder with version `v2.0`!

**Comment by tortmann** [comment]
We can further discuss the necessity for an English version during our next meeting as the customer doesn't necessarily require an EN version at this moment in time.
