### ISSUE TITLE
Define new tasks/issues (after interim)

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#80]
- define new tasks/issues for the dev-team which need to be done/considered

**Comment by amarbajric** [comment]
Proposal of new/additional tasks/issues can be found on the SharePoint:
`/Development/APs_Requirements/EBUSA_SWD_APs_29.04.18.pdf`

**ToDo:**
@tortmann i need your review upon the proposed tasks/issues and your opinion. If approved from you, we can create these tasks and put them in the backlog.

**Comment by tortmann** [comment]
@amarbajric thank you for the document. All tasks seem fine and I also definitely agree with your comments - therefore **APPROVED**. 

I would rate the importance of creating a guideline as high as the data model adaption since it is very important that everyone follows the same design guideline. I would suggest to assign this task to @deKilla since he has implemented the frontend baseline and will not be available for tasks after Wednesday. Please confirm @deKilla and @amarbajric.

We should probably have a skype meeting tomorrow morning regarding the data model adaption, maybe together with @loete if he is available.

Who do you think would be best suited to implemnt the ToDo of the RBAC service in case you are not planning on implementing it yourself?

I will create the tasks as defined in the document with a short description with reference to the document for more details if that is fine with you for the start. **more details - including a written/documented concept of how each component will be implemented should be done be each team member working on the tasks. **

Furthermore I will work on the review of PR #79 tomorrow morning.

**Comment by amarbajric** [comment]
> I would rate the importance of creating a guideline as high as the data model adaption since it is very important that everyone follows the same design guideline. I would suggest to assign this task to @deKilla since he has implemented the frontend baseline and will not be available for tasks after Wednesday. Please confirm @deKilla and @amarbajric.

I totally agree with you in this point.

> We should probably have a skype meeting tomorrow morning regarding the data model adaption, maybe together with @loete if he is available.

I also agree with you regarding this point. @loete and I already discussed about meeting virtually tomorrow. It would also be very helpful if you also participate @tortmann!

> Who do you think would be best suited to implemnt the ToDo of the RBAC service in case you are not planning on implementing it yourself?

I will finish this task after we have discussed the further things like the adaptation of the data model (again) and the meeting tomorrow about the process store service. Reason: I have worked now for some hours in the Gateway service (AuthenticationService to be precise) and I know the structure and files and behaviour of the service very well.

> I will create the tasks as defined in the document with a short description with reference to the document for more details if that is fine with you for the start. **more details - including a written/documented concept of how each component will be implemented should be done be each team member working on the tasks. **

Okay thank you very much for the initial creation of the tasks. Yes, we can ofc adapt the descriptions later on!

> Furthermore I will work on the review of PR #79 tomorrow morning.

Thank you!

**Comment by tortmann** [comment]
Alright thank you. I will be online at around 8:15am just give me a call when you wanna hold the meeting.
