### ISSUE TITLE
Approval View (Component)

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#87]
Special view for the Approver to be able to approve/reject and comment on process models.

For more details see document on SharePoint:
`/Development/APs_Requirements/EBUSA_SWD_APs_29.04.18.pdf`

**Comment by Graf-Carello** [comment]
@loete To include real data into the approval view, I would need the backend to give back a list of all process models which are not approved yet. To then display them in the approval view. Since at the moment, I am just displaying dummy data on the page. 
Further I would need the backend to also give back a list of all existing comments of a specific process model, to display them on the approval page. I guess this would be the comments from previous reviews, or if the designer of the process model responds to a RFC from some approval expert from EasyBiz. 

Another point, which probably is another task all together, is how we should handle displaying the model in the approval view and the store page. Together with @FleshMobProductions I tried to use an iFrame of the Modeller page, but I don't know if this is a good idea or will work properly. Maybe at least for the inital version of the approval page, just displaying textual information of a process model is enough to review it.
